language: go
sudo: false

env:
  - PATH="${PATH}:${HOME}/.local/bin"

install:
  - pip install --user --upgrade gsutil
  - bin/setup-ci-secrets $encrypted_5ba036e89377_key $encrypted_5ba036e89377_iv

script:
  - 'test "${TRAVIS_PULL_REQUEST}" = "false" && site/build-and-publish.sh || true'
